#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the food-safety seal images.

These are EVERMORE'S OWN badge artwork, not the certifying bodies' marks. The
MUI/BPJPH halal mark, the HACCP marks and the ISO 22000 mark are trademarks,
issued to a certificate holder with rules about size, colour and clear space.
They have to come from the issuer as files; drawing a lookalike would be both
an infringement and a misrepresentation.

So these are generic seals carrying the standard's NAME, which is a statement
of fact Steven has confirmed. The moment the real files exist, point the
sys_parameters at them and these stop being used — the template already renders
whatever path it is given.

One generator so the three share geometry exactly; three hand-drawn files would
drift in ring width and text placement, which is visible when they sit in a row.
"""

SIZE = 300
C = SIZE / 2

GOLD = "#D4AF37"
GOLD_DEEP = "#A8842A"
BEIGE = "#FFFAE0"
INK = "#1C3D34"


def scallops(count: int, radius: float, r: float) -> str:
    """The bumps around the rim that make a disc read as a seal."""
    import math
    out = []
    for i in range(count):
        a = 2 * math.pi * i / count
        cx = C + radius * math.cos(a)
        cy = C + radius * math.sin(a)
        out.append(f'<circle cx="{cx:.1f}" cy="{cy:.1f}" r="{r}" fill="{GOLD}"/>')
    return "\n    ".join(out)


def seal(lines, sub=None, title="") -> str:
    """One seal. `lines` is 1–2 lines of display text."""
    if len(lines) == 1:
        text = f'<text x="{C}" y="{C + 14}" class="big">{lines[0]}</text>'
    else:
        text = (f'<text x="{C}" y="{C - 8}" class="big">{lines[0]}</text>\n    '
                f'<text x="{C}" y="{C + 40}" class="big">{lines[1]}</text>')
    subline = (f'<text x="{C}" y="{C + 62}" class="sub">{sub}</text>' if sub else "")

    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}"
     width="{SIZE}" height="{SIZE}" role="img" aria-label="{title}">
  <title>{title}</title>
  <!-- Evermore's own seal artwork, NOT the certifying body's trademark.
       Generated by scripts/mkseals.py — edit there, not here. -->
  <style>
    .big {{ font-family: Georgia, "Times New Roman", serif; font-weight: 700;
            font-size: 46px; fill: {INK}; text-anchor: middle;
            letter-spacing: 1px; }}
    .sub {{ font-family: Georgia, "Times New Roman", serif; font-size: 15px;
            fill: {INK}; text-anchor: middle; letter-spacing: 3px; }}
  </style>
  <g>
    {scallops(30, 134, 11)}
  </g>
  <circle cx="{C}" cy="{C}" r="132" fill="{GOLD}"/>
  <circle cx="{C}" cy="{C}" r="120" fill="none" stroke="{GOLD_DEEP}" stroke-width="3"/>
  <circle cx="{C}" cy="{C}" r="112" fill="{BEIGE}"/>
  <circle cx="{C}" cy="{C}" r="103" fill="none" stroke="{GOLD_DEEP}"
          stroke-width="2" stroke-dasharray="2 7" stroke-linecap="round"/>
  {text}
  {subline}
</svg>
'''


SEALS = {
    "seal-halal.svg":      (["HALAL"], None, "Halal"),
    "seal-haccp.svg":      (["HACCP"], None,
                            "HACCP — Hazard Analysis and Critical Control Points"),
    "seal-iso-22000.svg":  (["ISO", "22000"], "FOOD SAFETY", "ISO 22000 food safety management"),
}

if __name__ == "__main__":
    import os
    out = "web/public/images"
    os.makedirs(out, exist_ok=True)
    for name, (lines, sub, title) in SEALS.items():
        path = os.path.join(out, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(seal(lines, sub, title))
        print(f"wrote {path}")
